name: ai_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/avatarx.png
   - assets/ai.png
   - assets/bg.jpg
   - assets/sound/getsound.mp3
   - assets/sound/sendsound.mp3
   - assets/sound/pop.mp3
